import React, { useState } from "react";
import { WeightConverter } from "./WeightConverter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { ShockSettings } from "./ShockSettings";
import { ShockFormFields } from "./ShockFormFields";
import { calculateShockSettings } from "@/utils/shockCalculations";
import { Download } from "lucide-react";
import jsPDF from "jspdf";

export const ShockSetupForm = () => {
  const { toast } = useToast();
  const [weight, setWeight] = useState(70);
  const [unit, setUnit] = useState<"kg" | "lbs">("kg");
  const [ridingStyle, setRidingStyle] = useState("trail");
  const [bikeType, setBikeType] = useState("full");
  const [travel, setTravel] = useState(150);
  const [preferredFeel, setPreferredFeel] = useState("balanced");
  const [trailCondition, setTrailCondition] = useState("technical");
  const [priority, setPriority] = useState("descending");

  const settings = calculateShockSettings(weight, unit, ridingStyle, preferredFeel);

  const handleReset = () => {
    setWeight(70);
    setUnit("kg");
    setRidingStyle("trail");
    setBikeType("full");
    setTravel(150);
    setPreferredFeel("balanced");
    setTrailCondition("technical");
    setPriority("descending");
    
    toast({
      title: "Settings Reset",
      description: "All values have been reset to defaults.",
    });
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.text("Fox Float X2 Shock Settings", 20, 20);
    
    // Add rider details
    doc.setFontSize(12);
    doc.text(`Rider Weight: ${weight} ${unit}`, 20, 40);
    doc.text(`Riding Style: ${ridingStyle}`, 20, 50);
    doc.text(`Bike Type: ${bikeType}`, 20, 60);
    doc.text(`Travel: ${travel}mm`, 20, 70);
    doc.text(`Preferred Feel: ${preferredFeel}`, 20, 80);
    doc.text(`Trail Condition: ${trailCondition}`, 20, 90);
    doc.text(`Priority: ${priority}`, 20, 100);
    
    // Add shock settings
    doc.setFontSize(16);
    doc.text("Recommended Settings:", 20, 120);
    
    doc.setFontSize(12);
    doc.text(`Air Pressure: ${settings.airPressure} PSI`, 20, 140);
    doc.text(`High-Speed Rebound (HSR): ${settings.hsr} clicks`, 20, 150);
    doc.text(`Low-Speed Rebound (LSR): ${settings.lsr} clicks`, 20, 160);
    doc.text(`High-Speed Compression (HSC): ${settings.hsc} clicks`, 20, 170);
    doc.text(`Low-Speed Compression (LSC): ${settings.lsc} clicks`, 20, 180);
    
    // Add footer
    doc.setFontSize(10);
    doc.text("Generated by Fox Float X2 Setup Guide", 20, 280);
    
    // Save the PDF
    doc.save("fox-float-x2-settings.pdf");
    
    toast({
      title: "PDF Downloaded",
      description: "Your shock settings have been saved as a PDF.",
    });
  };

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle>Shock Setup Calculator</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <WeightConverter
          weight={weight}
          unit={unit}
          onWeightChange={setWeight}
          onUnitChange={setUnit}
        />

        <ShockFormFields
          ridingStyle={ridingStyle}
          setRidingStyle={setRidingStyle}
          bikeType={bikeType}
          setBikeType={setBikeType}
          travel={travel}
          setTravel={setTravel}
          preferredFeel={preferredFeel}
          setPreferredFeel={setPreferredFeel}
          trailCondition={trailCondition}
          setTrailCondition={setTrailCondition}
          priority={priority}
          setPriority={setPriority}
        />

        <ShockSettings settings={settings} />

        <div className="flex justify-end gap-4">
          <Button variant="outline" onClick={handleReset}>
            Reset to Defaults
          </Button>
          <Button onClick={handleDownloadPDF}>
            <Download className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};